@c Copyright (C) 1988-2015 Free Software Foundation, Inc.
@c This is part of the GCC manual.
@c For copying conditions, see the file gcc.texi.

@node Contributing
@chapter Contributing to GCC Development

GCC のリリースがうまく動作することを保証する事前テストのお手伝いを
しても良いという方、あるいは GCC の改良作業をしてみたいという方は、
是非とも保守担当者 @code{gcc@@gcc.gnu.org} に連絡していただきたい。
事前テスターの方にはバグを報告するだけでなく、調査することも
やっていただきたい。

改良作業をしてみたい方は、提案されているプロジェクトについて尋ねてみて
欲しい。あるいは、自分自身のアイデアを提案して欲しい。
まだ作業を始めていないなら、始める前に @code{gcc@@gcc.gnu.org} に
連絡するのが良いだろう。
保守担当者は、読者の拡張を、GCC の他の部分や他の開発計画に
よりうまく適合させる方法を示唆することができるかもしれない。
